language: php

php:
    - "7.4"
    # - "7.3"
    # - "7.2"

env:
    global:
        - XDEBUG_MODE=coverage

sudo: false

git:
    submodules: false

before_script:
    - make install

script:
    - make test
